version: '3'
services:
  front:
    container_name: go-react-dev-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /src
    volumes:
      - ./front:/src:cached
      - /src/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      FRONT_HOST: 0.0.0.0
      API_HOST: http://api:3000
    tty: true

  api:
    container_name: go-react-dev-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api:/src:cached
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      GOOGLE_APPLICATION_CREDENTIALS: /src/serviceAccountKey.json
    tty: true
    depends_on:
      - db
  db:
    container_name: api_db
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
